import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'
import { formatCurrency } from './utils'

const PAGE_WIDTH = 210
const PAGE_HEIGHT = 297
const LOGO_SIZE = 25
/** Content width for tables and summary; used to center everything. */
const CONTENT_WIDTH = 120
const MARGIN_LEFT = (PAGE_WIDTH - CONTENT_WIDTH) / 2
const MARGIN_RIGHT = PAGE_WIDTH - MARGIN_LEFT - CONTENT_WIDTH
const MARGIN = MARGIN_LEFT

const TABLE_HEAD_STYLE = {
  fillColor: [22, 101, 86] as [number, number, number],
  textColor: 255,
  fontStyle: 'bold' as const,
}
const TABLE_BODY_STYLE = { textColor: 50 }
const TABLE_ALT_ROW = { fillColor: [249, 250, 251] as [number, number, number] }

type DocWithAutoTable = jsPDF & { lastAutoTable?: { finalY: number } }

function getFinalY(doc: DocWithAutoTable): number {
  return doc.lastAutoTable?.finalY ?? 0
}

interface HeaderOptions {
  business: {
    name: string
    type?: string
    state?: string
    city?: string
    logo?: string
  }
  reportTitle: string
  periodStart?: Date
  periodEnd?: Date
  asAtDate?: Date
}

/** Draw shared header. Returns Y position for content. Generated date is NOT in header (moved to footer). */
function drawHeader(doc: jsPDF, opts: HeaderOptions): number {
  const { business, reportTitle, periodStart, periodEnd, asAtDate } = opts
  let leftX = MARGIN
  const rightX = PAGE_WIDTH - MARGIN

  // Left: Logo (25x25) + Business Name + Address (small gray)
  if (business.logo) {
    try {
      const imgFormat = business.logo.indexOf('image/png') !== -1 ? 'PNG' : 'JPEG'
      doc.addImage(business.logo, imgFormat, MARGIN, 20, LOGO_SIZE, LOGO_SIZE)
    } catch {
      // ignore
    }
    leftX = MARGIN + LOGO_SIZE + 8
  }

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(business.name, leftX, 28)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  const address = [business.city, business.state].filter(Boolean).join(', ') || business.type || ''
  if (address) doc.text(address, leftX, 34)
  doc.setTextColor(0, 0, 0)

  // Right: Report Title (bold, large) + Date Range only (no Generated date here)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(reportTitle, rightX, 26, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  if (periodStart && periodEnd) {
    doc.text(`${format(periodStart, 'dd MMM yyyy')} – ${format(periodEnd, 'dd MMM yyyy')}`, rightX, 32, { align: 'right' })
  } else if (asAtDate) {
    doc.text(`As at ${format(asAtDate, 'dd MMM yyyy')}`, rightX, 32, { align: 'right' })
  }

  return 48
}

/** Footer: Generated date + Generated by Tally, same font size and style. */
function drawFooter(doc: jsPDF, generatedDate?: string): void {
  const dateStr = generatedDate ?? format(new Date(), 'dd MMM yyyy')
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated ${dateStr}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 16, { align: 'center' })
  doc.text('Generated by Tally', PAGE_WIDTH / 2, PAGE_HEIGHT - 12, { align: 'center' })
  doc.setTextColor(0, 0, 0)
}

/** Thin horizontal divider line above section content. */
function drawSectionDivider(doc: jsPDF, y: number): void {
  doc.setDrawColor(220, 220, 220)
  doc.setLineWidth(0.3)
  doc.line(MARGIN_LEFT, y, MARGIN_LEFT + CONTENT_WIDTH, y)
}

// --- Profit & Loss ---

export interface PDFData {
  business: {
    name: string
    type: string
    state: string
    city?: string
    logo?: string
  }
  period: { startDate: Date; endDate: Date }
  profitLoss: {
    revenue: { cash: number; credit: number; total: number }
    expenses: Record<string, number>
    totalExpenses: number
    netProfit: number
    profitMargin: number
  }
  transactions?: Array<{
    id: string
    transaction_type: string
    amount: number
    payment_method: string
    expense_category?: string
    notes?: string
    transaction_date: string
  }>
}

const EXPENSE_CATEGORY_LABELS: Record<string, string> = {
  stock_purchase: 'Stock Purchase',
  rent: 'Rent',
  utilities: 'Utilities',
  transport: 'Transport',
  salaries: 'Salaries',
  other: 'Other',
}

export function generateBusinessReportPDF(data: PDFData): void {
  const doc = new jsPDF() as DocWithAutoTable
  let currentY = drawHeader(doc, {
    business: data.business,
    reportTitle: 'Profit & Loss Statement',
    periodStart: data.period.startDate,
    periodEnd: data.period.endDate,
  })

  // Revenue table
  const revenueRows: [string, string][] = [
    ['Cash Sales', formatCurrency(data.profitLoss.revenue.cash)],
    ['Credit / Other Sales', formatCurrency(data.profitLoss.revenue.credit)],
    ['Total Revenue', formatCurrency(data.profitLoss.revenue.total)],
  ]
  autoTable(doc, {
    head: [['Revenue', 'Amount']],
    body: revenueRows,
    startY: currentY,
    headStyles: TABLE_HEAD_STYLE,
    bodyStyles: TABLE_BODY_STYLE,
    alternateRowStyles: TABLE_ALT_ROW,
    theme: 'plain',
    margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
    tableWidth: CONTENT_WIDTH,
    columnStyles: { 1: { halign: 'right' } },
  })
  currentY = getFinalY(doc) + 12

  // Expenses section
  const expenseEntries = Object.entries(data.profitLoss.expenses).filter(([, v]) => v > 0)
  const expenseRows: [string, string][] = expenseEntries.map(([cat, amt]) => [
    EXPENSE_CATEGORY_LABELS[cat] || cat,
    formatCurrency(amt),
  ])
  expenseRows.push(['Total Expenses', formatCurrency(data.profitLoss.totalExpenses)])
  autoTable(doc, {
    head: [['Expenses', 'Amount']],
    body: expenseRows,
    startY: currentY,
    headStyles: TABLE_HEAD_STYLE,
    bodyStyles: TABLE_BODY_STYLE,
    alternateRowStyles: TABLE_ALT_ROW,
    theme: 'plain',
    margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
    tableWidth: CONTENT_WIDTH,
    columnStyles: { 1: { halign: 'right' } },
  })
  currentY = getFinalY(doc) + 14

  // Net Profit (bold, emphasized at end of P&L)
  currentY += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Net Profit', MARGIN_LEFT, currentY)
  doc.text(formatCurrency(data.profitLoss.netProfit), MARGIN_LEFT + CONTENT_WIDTH, currentY, { align: 'right' })

  const generatedDate = format(new Date(), 'dd MMM yyyy')
  drawFooter(doc, generatedDate)
  doc.save(`${data.business.name}-Profit-Loss-${format(new Date(), 'yyyy-MM-dd')}.pdf`)
}

// --- Balance Sheet ---

export interface BalanceSheetPDFData {
  business: {
    name: string
    type: string
    state: string
    city?: string
    logo?: string
  }
  asAtDate?: Date
  balanceSheet: {
    assets: { cash: number; bank: number; receivables: number; inventory: number; total: number }
    liabilities: { payables: number; loans: number; total: number }
    equity: { startingCapital: number; retainedEarnings: number; total: number }
    balanceCheck?: number
    isBalanced?: boolean
  }
}

export function generateBalanceSheetPDF(data: BalanceSheetPDFData): void {
  const doc = new jsPDF() as DocWithAutoTable
  const generatedDate = format(new Date(), 'dd MMM yyyy')
  let currentY = drawHeader(doc, {
    business: data.business,
    reportTitle: 'Balance Sheet',
    asAtDate: data.asAtDate ?? new Date(),
  })

  const { assets, liabilities, equity } = data.balanceSheet

  // Divider line above Assets section
  drawSectionDivider(doc, currentY)
  currentY += 6

  // Assets table
  const assetRows: [string, string][] = [
    ['Cash', formatCurrency(assets.cash)],
    ['Bank', formatCurrency(assets.bank)],
    ['Receivables', formatCurrency(assets.receivables)],
    ['Inventory', formatCurrency(assets.inventory)],
    ['Total Assets', formatCurrency(assets.total)],
  ]
  autoTable(doc, {
    head: [['Assets', 'Amount']],
    body: assetRows,
    startY: currentY,
    headStyles: TABLE_HEAD_STYLE,
    bodyStyles: TABLE_BODY_STYLE,
    alternateRowStyles: TABLE_ALT_ROW,
    theme: 'plain',
    margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
    tableWidth: CONTENT_WIDTH,
    columnStyles: { 1: { halign: 'right' } },
  })
  currentY = getFinalY(doc) + 12

  // Liabilities & Equity table (centered)
  const liabRows: [string, string][] = [
    ['Payables', formatCurrency(liabilities.payables)],
    ['Loans', formatCurrency(liabilities.loans)],
    ['Total Liabilities', formatCurrency(liabilities.total)],
    ['Starting Capital', formatCurrency(equity.startingCapital)],
    ['Retained Earnings (Net Profit)', formatCurrency(equity.retainedEarnings)],
    ['Total Equity', formatCurrency(equity.total)],
  ]
  autoTable(doc, {
    head: [['Liabilities & Equity', 'Amount']],
    body: liabRows,
    startY: currentY,
    headStyles: TABLE_HEAD_STYLE,
    bodyStyles: TABLE_BODY_STYLE,
    alternateRowStyles: TABLE_ALT_ROW,
    theme: 'plain',
    margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
    tableWidth: CONTENT_WIDTH,
    columnStyles: { 1: { halign: 'right' } },
  })

  if (data.balanceSheet.isBalanced !== undefined) {
    currentY = getFinalY(doc) + 8
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(
      data.balanceSheet.isBalanced ? 'Balanced' : 'Not Balanced',
      PAGE_WIDTH / 2,
      currentY,
      { align: 'center' }
    )
  }

  drawFooter(doc, generatedDate)
  doc.save(`${data.business.name}-Balance-Sheet-${format(new Date(), 'yyyy-MM-dd')}.pdf`)
}

// --- Legacy comprehensive loan package (multi-page, kept for compatibility) ---

export interface ComprehensiveLoanPackagePDFData {
  business: { name: string; type: string; state: string; city?: string }
  period: { startDate: Date; endDate: Date }
  profitLoss: PDFData['profitLoss']
  balanceSheet: BalanceSheetPDFData['balanceSheet']
  transactions: PDFData['transactions']
}

export function generateComprehensiveLoanPackagePDF(data: ComprehensiveLoanPackagePDFData): void {
  generateBusinessReportPDF({
    business: data.business,
    period: data.period,
    profitLoss: data.profitLoss,
    transactions: data.transactions,
  })
}
